import Head from 'next/head'

import styles from '../styles/Home.module.scss'

import Navbar from './components/Navbar'
import LandingPage from './components/LandingPage'





export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Timekeepr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>

      <Navbar className={styles.navbar}/>
      <LandingPage className={styles.landingPage}/>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
